PROJECT = webserver_cowboy
PROJECT_DESCRIPTION = Cowboy webserver with ErlyDTL framework
PROJECT_VERSION = 0.1.0

DEPS = cowboy erlydtl
dep_cowboy_commit = 2.6.1
DEP_PLUGINS = cowboy


include erlang.mk
